using SCRM.Domain.MallManagement.Entitys;

namespace SCRM.Application.MallManagement.Dtos
{
    /// <summary>
    /// 数据传输对象扩展
    /// </summary>
    public static class MdmGoodsMstrDtoExtension {    
        /// <summary>
        /// 转换为实体
        /// </summary>
        /// <param name="dto">数据传输对象</param>
        public static MdmGoodsMstr ToEntity( this MdmGoodsMstrDto dto ) {
            if( dto == null )
                return new MdmGoodsMstr();
            return new MdmGoodsMstr() {
                Id = dto.Id,
                GOODS_NO = dto.GOODS_NO,
                GOODS_NAME = dto.GOODS_NAME,
                GOODS_PRINT_NAME = dto.GOODS_PRINT_NAME,
                GOODS_TYPE = dto.GOODS_TYPE,
                GOODS_LARGECLASS = dto.GOODS_LARGECLASS,
                GOODS_INCLASS = dto.GOODS_INCLASS,
                GOODS_SMALLCLASS = dto.GOODS_SMALLCLASS,
                GOODS_SUBCLASS = dto.GOODS_SUBCLASS,
                GOODS_LEVEL = dto.GOODS_LEVEL,
                PRODUCT_NO = dto.PRODUCT_NO,
                PRODUCT_NAME = dto.PRODUCT_NAME,
                BARCODE = dto.BARCODE,
                CAR_BRAND_ID = dto.CAR_BRAND_ID,
                CAR_BRAND_DESC = dto.CAR_BRAND_DESC,
                CAR_CLASS_ID = dto.CAR_CLASS_ID,
                CAR_CLASS_DESC = dto.CAR_CLASS_DESC,
                CAR_TYPE_ID = dto.CAR_TYPE_ID,
                CAR_TYPE_DESC = dto.CAR_TYPE_DESC,
                UNIT = dto.UNIT,
                SUBUNITVALUE = dto.SUBUNITVALUE,
                SUBUNITENABLED = dto.SUBUNITENABLED,
                SUBUNIT = dto.SUBUNIT,
                MNEMONIC_CODE = dto.MNEMONIC_CODE,
                GOODS_SPEC = dto.GOODS_SPEC,
                GOODS_MODEL = dto.GOODS_MODEL,
                GOODS_MATERIAL = dto.GOODS_MATERIAL,
                GOODS_SHELFLIFE = dto.GOODS_SHELFLIFE,
                MADE_IN = dto.MADE_IN,
                IS_TEMP = dto.IS_TEMP,
                GOODS_STATUS = dto.GOODS_STATUS,
                GOODS_SS_NEED = dto.GOODS_SS_NEED,
                GOODS_ORG_NO = dto.GOODS_ORG_NO,
                GOODS_RMK = dto.GOODS_RMK,
                IS_THREE_COMMITMENTS = dto.IS_THREE_COMMITMENTS,
                LIMITED_STORE_ID = dto.LIMITED_STORE_ID,
                LIMITED_STORE_NAME = dto.LIMITED_STORE_NAME,
                DATARIGHT = dto.DATARIGHT,
                ST_WORK_TIME = dto.ST_WORK_TIME,
                GOODS_PUR_ATTR = dto.GOODS_PUR_ATTR,
                GOODS_QA = dto.GOODS_QA,
                GOODS_BRAND = dto.GOODS_BRAND,
                GOODS_FUNC = dto.GOODS_FUNC,
                IS_COMBO = dto.IS_COMBO,
                PUR_ATTR = dto.PUR_ATTR,
                GOODS_PLM_ATTR1 = dto.GOODS_PLM_ATTR1,
                GOODS_ATTR = dto.GOODS_ATTR,
                CREATE_PSN = dto.CREATE_PSN,
                CREATE_DATE = dto.CREATE_DATE,
                UPDATE_PSN = dto.UPDATE_PSN,
                UPDATE_DATE = dto.UPDATE_DATE,
                CREATE_ORG_NO = dto.CREATE_ORG_NO,
                DEL_FLAG = dto.DEL_FLAG,
                GOODS_CONTENT = dto.GOODS_CONTENT,
                GOODS_ONSALE_DATE = dto.GOODS_ONSALE_DATE,
                GOODS_OFFSALE_DATE = dto.GOODS_OFFSALE_DATE,
                IS_SCORE_GET = dto.IS_SCORE_GET,
                SKU_PROPERTY_ID1 = dto.SKU_PROPERTY_ID1,
                SKU_PROPERTY_VALUE1 = dto.SKU_PROPERTY_VALUE1,
                SKU_PROPERTY_ID2 = dto.SKU_PROPERTY_ID2,
                SKU_PROPERTY_VALUE2 = dto.SKU_PROPERTY_VALUE2,
                SKU_PROPERTY_ID3 = dto.SKU_PROPERTY_ID3,
                SKU_PROPERTY_VALUE3 = dto.SKU_PROPERTY_VALUE3,
                SKU_PROPERTY_ID4 = dto.SKU_PROPERTY_ID4,
                SKU_PROPERTY_VALUE4 = dto.SKU_PROPERTY_VALUE4,
                SKU_PROPERTY_ID5 = dto.SKU_PROPERTY_ID5,
                SKU_PROPERTY_VALUE5 = dto.SKU_PROPERTY_VALUE5,
                OUT_SYS_ID_PINGAN = dto.OUT_SYS_ID_PINGAN,
                OUT_SYS_ID_CPIC = dto.OUT_SYS_ID_CPIC,
                OUT_SYS_ID_SHANGQI = dto.OUT_SYS_ID_SHANGQI,
                OUT_SYS_ID_PAZB = dto.OUT_SYS_ID_PAZB,
                GOODS_SORT_NO = dto.GOODS_SORT_NO,
                GL_ID = dto.GL_ID,
                SHOW_IN_LIST = dto.SHOW_IN_LIST,
                PROMOTION_ATTR = dto.PROMOTION_ATTR,
                SP_FLAG = dto.SP_FLAG,
                SP_SDATE = dto.SP_SDATE,
                SP_EDATE = dto.SP_EDATE,
                SP_QTY = dto.SP_QTY,
                SP_PRICE = dto.SP_PRICE,
                BG_NO = dto.BG_NO
            };
        }
        
        /// <summary>
        /// 转换为数据传输对象
        /// </summary>
        /// <param name="entity">实体</param>
        public static MdmGoodsMstrDto ToDto( this MdmGoodsMstr entity ) {
             if( entity == null )
                return new MdmGoodsMstrDto();
            return new MdmGoodsMstrDto {
                Id = entity.Id,
                GOODS_NO = entity.GOODS_NO,      
                GOODS_NAME = entity.GOODS_NAME,      
                GOODS_PRINT_NAME = entity.GOODS_PRINT_NAME,      
                GOODS_TYPE = entity.GOODS_TYPE,      
                GOODS_LARGECLASS = entity.GOODS_LARGECLASS,      
                GOODS_INCLASS = entity.GOODS_INCLASS,      
                GOODS_SMALLCLASS = entity.GOODS_SMALLCLASS,      
                GOODS_SUBCLASS = entity.GOODS_SUBCLASS,      
                GOODS_LEVEL = entity.GOODS_LEVEL,      
                PRODUCT_NO = entity.PRODUCT_NO,      
                PRODUCT_NAME = entity.PRODUCT_NAME,      
                BARCODE = entity.BARCODE,      
                CAR_BRAND_ID = entity.CAR_BRAND_ID,      
                CAR_BRAND_DESC = entity.CAR_BRAND_DESC,      
                CAR_CLASS_ID = entity.CAR_CLASS_ID,      
                CAR_CLASS_DESC = entity.CAR_CLASS_DESC,      
                CAR_TYPE_ID = entity.CAR_TYPE_ID,      
                CAR_TYPE_DESC = entity.CAR_TYPE_DESC,      
                UNIT = entity.UNIT,      
                SUBUNITVALUE = entity.SUBUNITVALUE,      
                SUBUNITENABLED = entity.SUBUNITENABLED,      
                SUBUNIT = entity.SUBUNIT,      
                MNEMONIC_CODE = entity.MNEMONIC_CODE,      
                GOODS_SPEC = entity.GOODS_SPEC,      
                GOODS_MODEL = entity.GOODS_MODEL,      
                GOODS_MATERIAL = entity.GOODS_MATERIAL,      
                GOODS_SHELFLIFE = entity.GOODS_SHELFLIFE,      
                MADE_IN = entity.MADE_IN,      
                IS_TEMP = entity.IS_TEMP,      
                GOODS_STATUS = entity.GOODS_STATUS,      
                GOODS_SS_NEED = entity.GOODS_SS_NEED,      
                GOODS_ORG_NO = entity.GOODS_ORG_NO,      
                GOODS_RMK = entity.GOODS_RMK,      
                IS_THREE_COMMITMENTS = entity.IS_THREE_COMMITMENTS,      
                LIMITED_STORE_ID = entity.LIMITED_STORE_ID,      
                LIMITED_STORE_NAME = entity.LIMITED_STORE_NAME,      
                DATARIGHT = entity.DATARIGHT,      
                ST_WORK_TIME = entity.ST_WORK_TIME,      
                GOODS_PUR_ATTR = entity.GOODS_PUR_ATTR,      
                GOODS_QA = entity.GOODS_QA,      
                GOODS_BRAND = entity.GOODS_BRAND,      
                GOODS_FUNC = entity.GOODS_FUNC,      
                IS_COMBO = entity.IS_COMBO,      
                PUR_ATTR = entity.PUR_ATTR,      
                GOODS_PLM_ATTR1 = entity.GOODS_PLM_ATTR1,      
                GOODS_ATTR = entity.GOODS_ATTR,      
                CREATE_PSN = entity.CREATE_PSN,      
                CREATE_DATE = entity.CREATE_DATE,      
                UPDATE_PSN = entity.UPDATE_PSN,      
                UPDATE_DATE = entity.UPDATE_DATE,      
                CREATE_ORG_NO = entity.CREATE_ORG_NO,      
                DEL_FLAG = entity.DEL_FLAG,      
                GOODS_CONTENT = entity.GOODS_CONTENT,      
                GOODS_ONSALE_DATE = entity.GOODS_ONSALE_DATE,      
                GOODS_OFFSALE_DATE = entity.GOODS_OFFSALE_DATE,      
                IS_SCORE_GET = entity.IS_SCORE_GET,      
                SKU_PROPERTY_ID1 = entity.SKU_PROPERTY_ID1,      
                SKU_PROPERTY_VALUE1 = entity.SKU_PROPERTY_VALUE1,      
                SKU_PROPERTY_ID2 = entity.SKU_PROPERTY_ID2,      
                SKU_PROPERTY_VALUE2 = entity.SKU_PROPERTY_VALUE2,      
                SKU_PROPERTY_ID3 = entity.SKU_PROPERTY_ID3,      
                SKU_PROPERTY_VALUE3 = entity.SKU_PROPERTY_VALUE3,      
                SKU_PROPERTY_ID4 = entity.SKU_PROPERTY_ID4,      
                SKU_PROPERTY_VALUE4 = entity.SKU_PROPERTY_VALUE4,      
                SKU_PROPERTY_ID5 = entity.SKU_PROPERTY_ID5,      
                SKU_PROPERTY_VALUE5 = entity.SKU_PROPERTY_VALUE5,      
                OUT_SYS_ID_PINGAN = entity.OUT_SYS_ID_PINGAN,      
                OUT_SYS_ID_CPIC = entity.OUT_SYS_ID_CPIC,      
                OUT_SYS_ID_SHANGQI = entity.OUT_SYS_ID_SHANGQI,      
                OUT_SYS_ID_PAZB = entity.OUT_SYS_ID_PAZB,      
                GOODS_SORT_NO = entity.GOODS_SORT_NO,      
                GL_ID = entity.GL_ID,      
                SHOW_IN_LIST = entity.SHOW_IN_LIST,      
                PROMOTION_ATTR = entity.PROMOTION_ATTR,      
                SP_FLAG = entity.SP_FLAG,      
                SP_SDATE = entity.SP_SDATE,      
                SP_EDATE = entity.SP_EDATE,      
                SP_QTY = entity.SP_QTY,      
                SP_PRICE = entity.SP_PRICE,      
                BG_NO = entity.BG_NO
            };
        }
    }
}