using SCRM.Domain.MallManagement.Entitys;

namespace SCRM.Application.MallManagement.Dtos
{
    /// <summary>
    /// 数据传输对象扩展
    /// </summary>
    public static class TxnSoMstrDtoExtension {    
        /// <summary>
        /// 转换为实体
        /// </summary>
        /// <param name="dto">数据传输对象</param>
        public static TxnSoMstr ToEntity( this TxnSoMstrDto dto ) {
            if( dto == null )
                return new TxnSoMstr();
            return new TxnSoMstr() {
                Id = dto.Id,
                SO_TYPE = dto.SO_TYPE,
                BIZ_TYPE = dto.BIZ_TYPE,
                SALE_TYPE = dto.SALE_TYPE,
                ORG_NO = dto.ORG_NO,
                BOOK_NO = dto.BOOK_NO,
                REF_NO = dto.REF_NO,
                QUEUE_NO = dto.QUEUE_NO,
                SA = dto.SA,
                SA_NAME = dto.SA_NAME,
                SALE_TEAM = dto.SALE_TEAM,
                SALE_PSN = dto.SALE_PSN,
                OLD_SO_NO = dto.OLD_SO_NO,
                CUS_NO = dto.CUS_NO,
                CUS_NAME = dto.CUS_NAME,
                MEMBER_NO = dto.MEMBER_NO,
                CARID = dto.CARID,
                VIN = dto.VIN,
                IN_MILEAGE = dto.IN_MILEAGE,
                NEXT_MMILEAGE = dto.NEXT_MMILEAGE,
                NEXT_MDATE = dto.NEXT_MDATE,
                IN_OIL = dto.IN_OIL,
                FCST_DELIVERY_DATE = dto.FCST_DELIVERY_DATE,
                IS_RTN_OLD_MATERIAL = dto.IS_RTN_OLD_MATERIAL,
                CUSTOMER_DESC = dto.CUSTOMER_DESC,
                MADVICE = dto.MADVICE,
                REMARK = dto.REMARK,
                SO_AMT = dto.SO_AMT,
                MATERIAL_AMT = dto.MATERIAL_AMT,
                MH_AMT = dto.MH_AMT,
                DISCOUNT_RATE = dto.DISCOUNT_RATE,
                DISCOUNT_AMT = dto.DISCOUNT_AMT,
                EXEMPT_AMT = dto.EXEMPT_AMT,
                YS_AMT = dto.YS_AMT,
                SS_MCARD = dto.SS_MCARD,
                SS_COUPON = dto.SS_COUPON,
                SS_SERVICE_CARD = dto.SS_SERVICE_CARD,
                SS_SCORE = dto.SS_SCORE,
                WIPE_ZERO_AMT = dto.WIPE_ZERO_AMT,
                IS_CREDIT = dto.IS_CREDIT,
                IS_PRINT = dto.IS_PRINT,
                PRINT_DATE = dto.PRINT_DATE,
                WORKFLOW_NO = dto.WORKFLOW_NO,
                INS_COMPANY = dto.INS_COMPANY,
                CONSIGNER = dto.CONSIGNER,
                CONSIGNER_PHONE = dto.CONSIGNER_PHONE,
                IS_INVOICE = dto.IS_INVOICE,
                PROCS_FINISH_TIME = dto.PROCS_FINISH_TIME,
                PROCS_FINISH_PSN = dto.PROCS_FINISH_PSN,
                PROCS_ORG_NO = dto.PROCS_ORG_NO,
                IS_RED = dto.IS_RED,
                IS_RVISIT = dto.IS_RVISIT,
                REWORK_DATE = dto.REWORK_DATE,
                REWORK_PSN = dto.REWORK_PSN,
                ITEM_SYNC_VERSION = dto.ITEM_SYNC_VERSION,
                IS_RESULT_REPORT = dto.IS_RESULT_REPORT,
                IS_WAIT = dto.IS_WAIT,
                PRE_DIAGNOSIS_RESULT = dto.PRE_DIAGNOSIS_RESULT,
                UDF1 = dto.UDF1,
                UDF2 = dto.UDF2,
                UDF3 = dto.UDF3,
                UDF4 = dto.UDF4,
                UDF5 = dto.UDF5,
                IS_AS = dto.IS_AS,
                SETTLE_PSN = dto.SETTLE_PSN,
                SETTLE_DATE = dto.SETTLE_DATE,
                SETTLE_CUS_AMT = dto.SETTLE_CUS_AMT,
                SETTLE_MFG_AMT = dto.SETTLE_MFG_AMT,
                SETTLE_3RD_AMT = dto.SETTLE_3RD_AMT,
                SETTLE_INNER_AMT = dto.SETTLE_INNER_AMT,
                GET_SCORE = dto.GET_SCORE,
                MFG_NO = dto.MFG_NO,
                MFG_NAME = dto.MFG_NAME,
                CONSIGN_ORG_NO = dto.CONSIGN_ORG_NO,
                CONSIGN_ORG_NAME = dto.CONSIGN_ORG_NAME,
                AR_CONFIRM = dto.AR_CONFIRM,
                AR_CONFIRM_DATE = dto.AR_CONFIRM_DATE,
                AR_CONFIRM_PSN = dto.AR_CONFIRM_PSN,
                SYNC_FLAG = dto.SYNC_FLAG,
                STATUS = dto.STATUS,
                CREATE_PSN = dto.CREATE_PSN,
                CREATE_DATE = dto.CREATE_DATE,
                UPDATE_PSN = dto.UPDATE_PSN,
                UPDATE_DATE = dto.UPDATE_DATE,
                DEL_FLAG = dto.DEL_FLAG,
                CLAIM_NO = dto.CLAIM_NO,
                CLAIM_SP_NO = dto.CLAIM_SP_NO,
                CLAIM_SP_NAME = dto.CLAIM_SP_NAME,
                SP_CLAIM_NO = dto.SP_CLAIM_NO,
                CLAIM_DECLARE_TIME = dto.CLAIM_DECLARE_TIME,
                CLAIM_DECLARE_PSN_ID = dto.CLAIM_DECLARE_PSN_ID,
                CLAIM_DECLARE_PSN_NAME = dto.CLAIM_DECLARE_PSN_NAME,
                CLAIM_CONFIRM_DATE = dto.CLAIM_CONFIRM_DATE,
                CLAIM_CONFIRM_PSN = dto.CLAIM_CONFIRM_PSN,
                CLAIM_AMT = dto.CLAIM_AMT,
                CLAIM_STATUS = dto.CLAIM_STATUS,
                CLAIM_RMK = dto.CLAIM_RMK,
                EXPRESS_NO = dto.EXPRESS_NO,
                DELIVERY_TYPE = dto.DELIVERY_TYPE,
                PAY_TYPE = dto.PAY_TYPE,
                INVOICE_TYPE = dto.INVOICE_TYPE,
                INVOICE_TITLE = dto.INVOICE_TITLE,
                SO_ORDERNO = dto.SO_ORDERNO,
                BG_NO = dto.BG_NO,
                IS_PUSH = dto.IS_PUSH,
                WX_SO_ORDERNO = dto.WX_SO_ORDERNO,
                SETTLE_WAY = dto.SETTLE_WAY
            };
        }
        
        /// <summary>
        /// 转换为数据传输对象
        /// </summary>
        /// <param name="entity">实体</param>
        public static TxnSoMstrDto ToDto( this TxnSoMstr entity ) {
             if( entity == null )
                return new TxnSoMstrDto();
            return new TxnSoMstrDto {
                Id = entity.Id,
                SO_TYPE = entity.SO_TYPE,      
                BIZ_TYPE = entity.BIZ_TYPE,      
                SALE_TYPE = entity.SALE_TYPE,      
                ORG_NO = entity.ORG_NO,      
                BOOK_NO = entity.BOOK_NO,      
                REF_NO = entity.REF_NO,      
                QUEUE_NO = entity.QUEUE_NO,      
                SA = entity.SA,      
                SA_NAME = entity.SA_NAME,      
                SALE_TEAM = entity.SALE_TEAM,      
                SALE_PSN = entity.SALE_PSN,      
                OLD_SO_NO = entity.OLD_SO_NO,      
                CUS_NO = entity.CUS_NO,      
                CUS_NAME = entity.CUS_NAME,      
                MEMBER_NO = entity.MEMBER_NO,      
                CARID = entity.CARID,      
                VIN = entity.VIN,      
                IN_MILEAGE = entity.IN_MILEAGE,      
                NEXT_MMILEAGE = entity.NEXT_MMILEAGE,      
                NEXT_MDATE = entity.NEXT_MDATE,      
                IN_OIL = entity.IN_OIL,      
                FCST_DELIVERY_DATE = entity.FCST_DELIVERY_DATE,      
                IS_RTN_OLD_MATERIAL = entity.IS_RTN_OLD_MATERIAL,      
                CUSTOMER_DESC = entity.CUSTOMER_DESC,      
                MADVICE = entity.MADVICE,      
                REMARK = entity.REMARK,      
                SO_AMT = entity.SO_AMT,      
                MATERIAL_AMT = entity.MATERIAL_AMT,      
                MH_AMT = entity.MH_AMT,      
                DISCOUNT_RATE = entity.DISCOUNT_RATE,      
                DISCOUNT_AMT = entity.DISCOUNT_AMT,      
                EXEMPT_AMT = entity.EXEMPT_AMT,      
                YS_AMT = entity.YS_AMT,      
                SS_MCARD = entity.SS_MCARD,      
                SS_COUPON = entity.SS_COUPON,      
                SS_SERVICE_CARD = entity.SS_SERVICE_CARD,      
                SS_SCORE = entity.SS_SCORE,      
                WIPE_ZERO_AMT = entity.WIPE_ZERO_AMT,      
                IS_CREDIT = entity.IS_CREDIT,      
                IS_PRINT = entity.IS_PRINT,      
                PRINT_DATE = entity.PRINT_DATE,      
                WORKFLOW_NO = entity.WORKFLOW_NO,      
                INS_COMPANY = entity.INS_COMPANY,      
                CONSIGNER = entity.CONSIGNER,      
                CONSIGNER_PHONE = entity.CONSIGNER_PHONE,      
                IS_INVOICE = entity.IS_INVOICE,      
                PROCS_FINISH_TIME = entity.PROCS_FINISH_TIME,      
                PROCS_FINISH_PSN = entity.PROCS_FINISH_PSN,      
                PROCS_ORG_NO = entity.PROCS_ORG_NO,      
                IS_RED = entity.IS_RED,      
                IS_RVISIT = entity.IS_RVISIT,      
                REWORK_DATE = entity.REWORK_DATE,      
                REWORK_PSN = entity.REWORK_PSN,      
                ITEM_SYNC_VERSION = entity.ITEM_SYNC_VERSION,      
                IS_RESULT_REPORT = entity.IS_RESULT_REPORT,      
                IS_WAIT = entity.IS_WAIT,      
                PRE_DIAGNOSIS_RESULT = entity.PRE_DIAGNOSIS_RESULT,      
                UDF1 = entity.UDF1,      
                UDF2 = entity.UDF2,      
                UDF3 = entity.UDF3,      
                UDF4 = entity.UDF4,      
                UDF5 = entity.UDF5,      
                IS_AS = entity.IS_AS,      
                SETTLE_PSN = entity.SETTLE_PSN,      
                SETTLE_DATE = entity.SETTLE_DATE,      
                SETTLE_CUS_AMT = entity.SETTLE_CUS_AMT,      
                SETTLE_MFG_AMT = entity.SETTLE_MFG_AMT,      
                SETTLE_3RD_AMT = entity.SETTLE_3RD_AMT,      
                SETTLE_INNER_AMT = entity.SETTLE_INNER_AMT,      
                GET_SCORE = entity.GET_SCORE,      
                MFG_NO = entity.MFG_NO,      
                MFG_NAME = entity.MFG_NAME,      
                CONSIGN_ORG_NO = entity.CONSIGN_ORG_NO,      
                CONSIGN_ORG_NAME = entity.CONSIGN_ORG_NAME,      
                AR_CONFIRM = entity.AR_CONFIRM,      
                AR_CONFIRM_DATE = entity.AR_CONFIRM_DATE,      
                AR_CONFIRM_PSN = entity.AR_CONFIRM_PSN,      
                SYNC_FLAG = entity.SYNC_FLAG,      
                STATUS = entity.STATUS,      
                CREATE_PSN = entity.CREATE_PSN,      
                CREATE_DATE = entity.CREATE_DATE,      
                UPDATE_PSN = entity.UPDATE_PSN,      
                UPDATE_DATE = entity.UPDATE_DATE,      
                DEL_FLAG = entity.DEL_FLAG,      
                CLAIM_NO = entity.CLAIM_NO,      
                CLAIM_SP_NO = entity.CLAIM_SP_NO,      
                CLAIM_SP_NAME = entity.CLAIM_SP_NAME,      
                SP_CLAIM_NO = entity.SP_CLAIM_NO,      
                CLAIM_DECLARE_TIME = entity.CLAIM_DECLARE_TIME,      
                CLAIM_DECLARE_PSN_ID = entity.CLAIM_DECLARE_PSN_ID,      
                CLAIM_DECLARE_PSN_NAME = entity.CLAIM_DECLARE_PSN_NAME,      
                CLAIM_CONFIRM_DATE = entity.CLAIM_CONFIRM_DATE,      
                CLAIM_CONFIRM_PSN = entity.CLAIM_CONFIRM_PSN,      
                CLAIM_AMT = entity.CLAIM_AMT,      
                CLAIM_STATUS = entity.CLAIM_STATUS,      
                CLAIM_RMK = entity.CLAIM_RMK,      
                EXPRESS_NO = entity.EXPRESS_NO,      
                DELIVERY_TYPE = entity.DELIVERY_TYPE,      
                PAY_TYPE = entity.PAY_TYPE,      
                INVOICE_TYPE = entity.INVOICE_TYPE,      
                INVOICE_TITLE = entity.INVOICE_TITLE,      
                SO_ORDERNO = entity.SO_ORDERNO,      
                BG_NO = entity.BG_NO,      
                IS_PUSH = entity.IS_PUSH,      
                WX_SO_ORDERNO = entity.WX_SO_ORDERNO,      
                SETTLE_WAY = entity.SETTLE_WAY
            };
        }
    }
}